# -*- coding: utf-8 -*-

"""
/***************************************************************************
 SpatialStatistics
                                 A QGIS plugin
 This plugin provide spatial statistic tool
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-13
        copyright            : (C) 2025 by nbayashi
        email                : naoya_nstyle@hotmail.co.jp
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'nbayashi'
__date__ = '2025-04-13'
__copyright__ = '(C) 2025 by nbayashi'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'
import os
from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtGui import QIcon
from .r_runner_plugin_dialog import RRunnerPluginDialog
from qgis.core import QgsProcessingProvider
from .processing import RScriptProcessingProvider
from qgis.core import QgsApplication

from .processing_provider.spatial_statistics_provider import SpatialStatisticsProvider

class RRunnerPlugin:
    def __init__(self, iface):
        self.iface = iface
        self.action = None
        self.dialog = None
        self.provider = None

    def initGui(self):
        self.initProcessing()
        icon_path = ''  # Add icon if needed
        self.action = QAction("R Runner Plugin", self.iface.mainWindow())
        self.action.triggered.connect(self.show_dialog)
        self.iface.addPluginToMenu("R Runner", self.action)


    def initProcessing(self):
        self.provider = SpatialStatisticsProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def unload(self):
        self.iface.removePluginMenu("R Runner", self.action)
        QgsApplication.processingRegistry().removeProvider(self.provider)


    def show_dialog(self):
        self.dialog = RRunnerPluginDialog()
        self.dialog.show()