# -*- coding: utf-8 -*-

"""
/***************************************************************************
 SpatialStatistics
                                 A QGIS plugin
 This plugin provide spatial statistic tool
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-13
        copyright            : (C) 2025 by nbayashi
        email                : naoya_nstyle@hotmail.co.jp
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'nbayashi'
__date__ = '2025-04-13'
__copyright__ = '(C) 2025 by nbayashi'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import QgsProcessingProvider
from .r_adjacency_matrix_algorithm import AdjacencyMatrixAlgorithm
from .r_knearneigh_algorithm import KnearneighAlgorithm
from .r_dnearneigh_algorithm import DnearneighAlgorithm
from .gisa.gisa_adjacency_matrix_algorithm import GISAAdjacencyMatrixAlgorithm
from .gisa.gisa_knearneigh_algorithm import GISAKnearneighAlgorithm
from .gisa.gisa_dnearneigh_algorithm import GISADnearneighAlgorithm
from .lisa.lisa_adjacency_matrix_algorithm import LISAAdjacencyMatrixAlgorithm
from .lisa.lisa_dnearneigh_algorithm import LISADnearneighAlgorithm


class AdjacencyMatrixProvider(QgsProcessingProvider):

    def __init__(self):
        """
        Default constructor.
        """
        QgsProcessingProvider.__init__(self)

    def unload(self):
        """
        Unloads the provider. Any tear-down steps required by the provider
        should be implemented here.
        """
        pass

    def loadAlgorithms(self):
        """
        Loads all algorithms belonging to this provider.
        """
        self.addAlgorithm(AdjacencyMatrixAlgorithm())
        self.addAlgorithm(KnearneighAlgorithm())
        self.addAlgorithm(DnearneighAlgorithm())
        # add GISA algorithms
        self.addAlgorithm(GISAAdjacencyMatrixAlgorithm())
        self.addAlgorithm(GISAKnearneighAlgorithm())
        self.addAlgorithm(GISADnearneighAlgorithm())
        # add LISA algorithms
        self.addAlgorithm(LISAAdjacencyMatrixAlgorithm())
        self.addAlgorithm(LISADnearneighAlgorithm())
        # add additional algorithms here
        # self.addAlgorithm(MyOtherAlgorithm())


    def id(self):
        """
        Returns the unique provider id, used for identifying the provider. This
        string should be a unique, short, character only string, eg "qgis" or
        "gdal". This string should not be localised.
        """
        return 'rspatialstatistics'

    def name(self):
        """
        Returns the provider name, which is used to describe the provider
        within the GUI.

        This string should be short (e.g. "Lastools") and localised.
        """
        return self.tr('R Spatial Statistics')

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        return QgsProcessingProvider.icon(self)

    def longName(self):
        """
        Returns the a longer version of the provider name, which can include
        extra details such as version numbers. E.g. "Lastools LIDAR tools
        (version 2.2.1)". This string should be localised. The default
        implementation returns the same string as name().
        """
        return self.name()
